/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./templates/**/*.html", "./app/**/*.py"],
  safelist: [
    "btn-primary",
    "btn-secondary",
    "btn-cta",
    "card-commerce",
    "chip-filter",
    "chip-active",
    "chip-suggestion",
    "prose-assistant",
    "assistant-products",
    "justify-start",
    "justify-end",
    "max-w-[85%]",
    "rounded-xl",
    "rounded-bl-md",
    "rounded-br-md",
    "rounded-tl-none",
    "rounded-tr-none",
    "whitespace-pre-wrap",
    "border-t",
    "mt-3",
    "pt-3",
    "ml-[280px]",
    "w-[280px]",
    "bg-sidebar-bg",
    "bg-surface-muted",
    "text-on-surface-variant",
    "material-symbols-outlined",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#191c1d",
        "tertiary-fixed-dim": "#edbf7f",
        "text-main": "#333333",
        "on-error": "#ffffff",
        "surface-dim": "#d9dadb",
        "on-secondary-container": "#6a4b00",
        canvas: "#FFFFFF",
        "secondary-fixed-dim": "#ffbb1e",
        "secondary-fixed": "#ffdea7",
        "on-secondary": "#ffffff",
        outline: "#7a7581",
        "inverse-primary": "#d1bcff",
        "primary-fixed": "#eaddff",
        "on-primary": "#ffffff",
        "surface-variant": "#e1e3e4",
        surface: "#f8f9fa",
        "surface-tint": "#68519b",
        "surface-muted": "#F0EEFA",
        "primary-fixed-dim": "#d1bcff",
        "primary-container": "#422b73",
        "on-primary-fixed": "#230654",
        "surface-container-high": "#e7e8e9",
        "inverse-on-surface": "#f0f1f2",
        "sidebar-bg": "#422B73",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-fixed": "#291800",
        "surface-bright": "#f8f9fa",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "on-primary-container": "#af96e6",
        "on-secondary-fixed": "#271900",
        "on-tertiary-fixed-variant": "#60410c",
        "on-secondary-fixed-variant": "#5e4200",
        "on-tertiary-container": "#c69b5f",
        "secondary-container": "#fcb812",
        secondary: "#7c5800",
        "tertiary-fixed": "#ffddb2",
        "on-surface-variant": "#494550",
        "error-container": "#ffdad6",
        "on-background": "#191c1d",
        primary: "#2c125c",
        "on-primary-fixed-variant": "#503982",
        "inverse-surface": "#2e3132",
        "tertiary-container": "#503300",
        tertiary: "#341f00",
        "surface-container": "#edeeef",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e1e3e4",
        background: "#f8f9fa",
        "outline-variant": "#cbc4d1",
        // Legacy aliases — checkout partials and tests
        kapruka: {
          50: "#f5f0ff",
          100: "#eaddff",
          200: "#d1bcff",
          300: "#af96e6",
          400: "#68519b",
          500: "#503982",
          600: "#2c125c",
          700: "#422b73",
          800: "#230654",
          900: "#1a0440",
          950: "#0f0228",
        },
        commerce: {
          cream: "#FFFFFF",
          parchment: "#e1e3e4",
          gold: "#fcb812",
          amber: "#ffbb1e",
          terracotta: "#7c5800",
          spice: "#503300",
          ink: "#191c1d",
          muted: "#494550",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "2rem",
        "stack-sm": "0.5rem",
        "gutter-grid": "1.5rem",
        "stack-md": "1rem",
        "margin-page": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
