#!/usr/bin/env bash
# Generate a gitignored .env for local development using gcloud and python.
#
# Fetches GCP_PROJECT_ID, GCP_LOCATION, and a Generative Language API key via
# gcloud. Generates SESSION_SECRET with python secrets.token_urlsafe.
# Neo4j AuraDB and Zep Cloud values remain manual placeholders (see .env.example).
#
# Usage:
#   ./scripts/bootstrap_env.sh          # create .env (fails if it exists)
#   ./scripts/bootstrap_env.sh --force  # overwrite existing .env
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${BOOTSTRAP_ENV_FILE:-${ROOT_DIR}/.env}"
FORCE=false
KEY_DISPLAY_NAME="agentic-kapruka-local-dev"
DEFAULT_GCP_LOCATION="us-central1"
KAPRUKA_MCP_DEFAULT="https://mcp.kapruka.com/mcp"

usage() {
  cat <<'EOF'
Usage: bootstrap_env.sh [--force]

Generate .env for local development:
  - GCP_PROJECT_ID from: gcloud config get-value project
  - GCP_LOCATION from:   gcloud config get-value compute/region (fallback us-central1)
  - GOOGLE_API_KEY from: gcloud services api-keys (generativelanguage.googleapis.com)
  - SESSION_SECRET from: python secrets.token_urlsafe(48)
  - REDIS_URL and KAPRUKA_MCP_URL defaults; Neo4j and Zep remain placeholders

Options:
  --force, -f   Overwrite an existing .env file
  --help, -h    Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force | -f)
      FORCE=true
      shift
      ;;
    --help | -h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -f "${ENV_FILE}" && "${FORCE}" != "true" ]]; then
  echo "Error: ${ENV_FILE} already exists. Use --force to overwrite." >&2
  exit 1
fi

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Error: required command not found: $1" >&2
    exit 1
  fi
}

require_cmd gcloud
require_cmd python3

gcloud_config_value() {
  local value
  value="$(gcloud config get-value "$1" 2>/dev/null | tr -d '[:space:]' || true)"
  if [[ -z "${value}" || "${value}" == "(unset)" ]]; then
    return 1
  fi
  printf '%s' "${value}"
}

GCP_PROJECT_ID="$(gcloud_config_value project || true)"
if [[ -z "${GCP_PROJECT_ID}" ]]; then
  echo "Error: gcloud project is not set. Run: gcloud config set project PROJECT_ID" >&2
  exit 1
fi

if GCP_LOCATION="$(gcloud_config_value compute/region)"; then
  :
else
  GCP_LOCATION="${DEFAULT_GCP_LOCATION}"
  echo "Note: gcloud compute/region is unset; using ${GCP_LOCATION}" >&2
fi

fetch_or_create_api_key() {
  local project="$1"
  local display_name="$2"
  local existing

  existing="$(
    gcloud services api-keys list \
      --project="${project}" \
      --filter="displayName=\"${display_name}\"" \
      --format='value(name)' \
      --limit=1 2>/dev/null || true
  )"

  if [[ -n "${existing}" ]]; then
    echo "Reusing existing API key: ${display_name}" >&2
    printf '%s' "${existing}"
    return 0
  fi

  echo "Creating Generative Language API key (${display_name})..." >&2
  gcloud services api-keys create \
    --project="${project}" \
    --display-name="${display_name}" \
    --api-target=service=generativelanguage.googleapis.com \
    --format='value(name)'
}

KEY_RESOURCE="$(fetch_or_create_api_key "${GCP_PROJECT_ID}" "${KEY_DISPLAY_NAME}")"
if [[ -z "${KEY_RESOURCE}" ]]; then
  echo "Error: failed to resolve API key resource name" >&2
  exit 1
fi

GOOGLE_API_KEY="$(
  gcloud services api-keys get-key-string "${KEY_RESOURCE}" --format='value(keyString)'
)"
if [[ -z "${GOOGLE_API_KEY}" ]]; then
  echo "Error: failed to fetch API key string" >&2
  exit 1
fi

SESSION_SECRET="$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")"

cat >"${ENV_FILE}" <<EOF
# Generated by scripts/bootstrap_env.sh — do not commit (see .gitignore).
# Fill in Neo4j AuraDB and Zep Cloud values from their consoles before running the app.

REDIS_URL=redis://localhost:6379/0

NEO4J_URI=bolt+s://xxxxxxxx.databases.neo4j.io
NEO4J_USER=neo4j
NEO4J_PASSWORD=your-neo4j-password

ZEP_API_KEY=your-zep-api-key

GOOGLE_API_KEY=${GOOGLE_API_KEY}
GCP_PROJECT_ID=${GCP_PROJECT_ID}
GCP_LOCATION=${GCP_LOCATION}

KAPRUKA_MCP_URL=${KAPRUKA_MCP_DEFAULT}

SESSION_SECRET=${SESSION_SECRET}
EOF

chmod 600 "${ENV_FILE}"
echo "Wrote ${ENV_FILE}"
echo "Next: set NEO4J_URI, NEO4J_PASSWORD, and ZEP_API_KEY, then run: uvicorn app.main:app --reload"
