#!/usr/bin/env bash
# Generate a gitignored .env for local development using gcloud and python.
#
# Reads GCP_PROJECT_ID and GCP_LOCATION from gcloud. Gemini chat uses Vertex AI
# via Application Default Credentials (gcloud auth application-default login).
# Generates SESSION_SECRET with python secrets.token_urlsafe.
# Neo4j AuraDB and Zep Cloud values remain manual placeholders (see .env.example).
#
# Usage:
#   ./scripts/bootstrap_env.sh          # create .env (fails if it exists)
#   ./scripts/bootstrap_env.sh --force  # overwrite existing .env
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${BOOTSTRAP_ENV_FILE:-${ROOT_DIR}/.env}"
FORCE=false
DEFAULT_GCP_LOCATION="us-central1"
KAPRUKA_MCP_DEFAULT="https://mcp.kapruka.com/mcp"

usage() {
  cat <<'EOF'
Usage: bootstrap_env.sh [--force]

Generate .env for local development:
  - GCP_PROJECT_ID from: gcloud config get-value project
  - GCP_LOCATION from:   gcloud config get-value compute/region (fallback us-central1)
  - GEMINI_BACKEND=vertex (Gemini via Vertex AI + ADC, not API key billing)
  - SESSION_SECRET from: python secrets.token_urlsafe(48)
  - REDIS_URL and KAPRUKA_MCP_URL defaults; Neo4j and Zep remain placeholders

After bootstrap, authenticate for Vertex AI:
  gcloud auth application-default login
  # or: export GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account-key.json

Options:
  --force, -f   Overwrite an existing .env file
  --help, -h    Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force | -f)
      FORCE=true
      shift
      ;;
    --help | -h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -f "${ENV_FILE}" && "${FORCE}" != "true" ]]; then
  echo "Error: ${ENV_FILE} already exists. Use --force to overwrite." >&2
  exit 1
fi

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Error: required command not found: $1" >&2
    exit 1
  fi
}

require_cmd gcloud
require_cmd python3

gcloud_config_value() {
  local value
  value="$(gcloud config get-value "$1" 2>/dev/null | tr -d '[:space:]' || true)"
  if [[ -z "${value}" || "${value}" == "(unset)" ]]; then
    return 1
  fi
  printf '%s' "${value}"
}

GCP_PROJECT_ID="$(gcloud_config_value project || true)"
if [[ -z "${GCP_PROJECT_ID}" ]]; then
  echo "Error: gcloud project is not set. Run: gcloud config set project PROJECT_ID" >&2
  exit 1
fi

if GCP_LOCATION="$(gcloud_config_value compute/region)"; then
  :
else
  GCP_LOCATION="${DEFAULT_GCP_LOCATION}"
  echo "Note: gcloud compute/region is unset; using ${GCP_LOCATION}" >&2
fi

SESSION_SECRET="$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")"

cat >"${ENV_FILE}" <<EOF
# Generated by scripts/bootstrap_env.sh — do not commit (see .gitignore).
# Fill in Neo4j AuraDB and Zep Cloud values from their consoles before running the app.
# Gemini uses Vertex AI (service account / ADC). Run: gcloud auth application-default login

REDIS_URL=redis://localhost:6379/0

NEO4J_URI=bolt+s://xxxxxxxx.databases.neo4j.io
NEO4J_USER=neo4j
NEO4J_PASSWORD=your-neo4j-password

ZEP_API_KEY=your-zep-api-key

GEMINI_BACKEND=vertex
GCP_PROJECT_ID=${GCP_PROJECT_ID}
GCP_LOCATION=${GCP_LOCATION}

KAPRUKA_MCP_URL=${KAPRUKA_MCP_DEFAULT}

SESSION_SECRET=${SESSION_SECRET}
EOF

chmod 600 "${ENV_FILE}"
echo "Wrote ${ENV_FILE}"
echo "Next:"
echo "  1. gcloud auth application-default login  (or set GOOGLE_APPLICATION_CREDENTIALS)"
echo "  2. Set NEO4J_URI, NEO4J_PASSWORD, and ZEP_API_KEY in .env"
echo "  3. docker run -d -p 6379:6379 redis/redis-stack-server:latest"
echo "  4. uvicorn app.main:app --reload"
