# Generate a gitignored .env for local development using Python.
# Windows PowerShell port of scripts/bootstrap_env.sh
#
# Usage:
#   .\scripts\bootstrap_env.ps1          # create .env (fails if it exists)
#   .\scripts\bootstrap_env.ps1 -Force   # overwrite existing .env

[CmdletBinding()]
param(
    [switch]$Force,
    [switch]$Help
)

$ErrorActionPreference = "Stop"

$RootDir = Split-Path -Parent $PSScriptRoot
$EnvFile = if ($env:BOOTSTRAP_ENV_FILE) { $env:BOOTSTRAP_ENV_FILE } else { Join-Path $RootDir ".env" }
$KaprukaMcpDefault = "https://mcp.kapruka.com/mcp"

function Show-Usage {
    @"
Usage: bootstrap_env.ps1 [-Force]

Generate .env for local development:
  - SESSION_SECRET from: python secrets.token_urlsafe(48)
  - REDIS_URL and KAPRUKA_MCP_URL defaults; NVIDIA, Neo4j, and Zep remain placeholders

Options:
  -Force   Overwrite an existing .env file
  -Help    Show this help
"@ | Write-Host
}

if ($Help) {
    Show-Usage
    exit 0
}

if ((Test-Path $EnvFile) -and -not $Force) {
    Write-Error "Error: $EnvFile already exists. Use -Force to overwrite."
    exit 1
}

function Resolve-Python {
    foreach ($name in @("python", "python3", "py")) {
        $cmd = Get-Command $name -ErrorAction SilentlyContinue
        if ($cmd) {
            return $cmd.Source
        }
    }
    Write-Error "Error: required command not found: python"
    exit 1
}

$Python = Resolve-Python
$SessionSecret = & $Python -c "import secrets; print(secrets.token_urlsafe(48))"
if ($LASTEXITCODE -ne 0 -or -not $SessionSecret) {
    Write-Error "Failed to generate SESSION_SECRET"
    exit 1
}

$content = @"
# Generated by scripts/bootstrap_env.ps1 — do not commit (see .gitignore).
# Fill in Neo4j AuraDB and Zep Cloud values from their consoles before running the app.
# Gemini uses Vertex AI (service account / ADC). Run: gcloud auth application-default login

REDIS_URL=redis://localhost:6379/0

NEO4J_URI=bolt+s://xxxxxxxx.databases.neo4j.io
NEO4J_USER=neo4j
NEO4J_PASSWORD=your-neo4j-password

ZEP_API_KEY=your-zep-api-key

NVIDIA_API_KEY=your-nvidia-api-key

KAPRUKA_MCP_URL=$KaprukaMcpDefault

SESSION_SECRET=$SessionSecret
"@

Set-Content -Path $EnvFile -Value $content -Encoding UTF8

# Restrict ACL to current user (best-effort equivalent of chmod 600)
try {
    icacls $EnvFile /inheritance:r /grant:r "${env:USERNAME}:(R,W)" 1>$null 2>$null | Out-Null
}
catch {
    # Non-fatal on systems without icacls permissions
}

Write-Host "Wrote $EnvFile"
Write-Host "Next:"
Write-Host "  1. gcloud auth application-default login  (or set GOOGLE_APPLICATION_CREDENTIALS)"
Write-Host "  2. Set NEO4J_URI, NEO4J_PASSWORD, and ZEP_API_KEY in .env"
Write-Host "  3. .\scripts\dev.ps1 start"
Write-Host "  4. Or: uvicorn app.main:app --reload"
